# Generated by Django 6.1 on 2026-08-31 07:20

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CableSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='型号')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('voltage', models.CharField(default='0.6/1kV', max_length=20, verbose_name='电压等级')),
                ('conductor', models.CharField(choices=[('CU', '铜'), ('AL', '铝')], default='CU', max_length=2, verbose_name='导体材料')),
                ('has_sheath', models.BooleanField(default=True, verbose_name='有护套')),
                ('insulation_thickness', models.JSONField(default=dict, verbose_name='绝缘厚度表 mm')),
                ('core_options', models.JSONField(default=list, verbose_name='芯数组合')),
                ('sections', models.JSONField(default=list, verbose_name='生成截面列表')),
                ('conductor_od_factor', models.DecimalField(decimal_places=3, default=1.18, help_text='导体外径 ≈ 系数 × √截面（绞合紧压）', max_digits=5, verbose_name='导体直径系数')),
                ('lay_factor', models.DecimalField(decimal_places=3, default=1.02, max_digits=5, verbose_name='绞合系数')),
                ('active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '型号系列',
                'verbose_name_plural': '型号系列',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='客户名称')),
                ('level', models.CharField(choices=[('A', 'A类（重点）'), ('B', 'B类（普通）'), ('C', 'C类（零售）')], default='B', max_length=1, verbose_name='客户等级')),
                ('discount', models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text='报价单默认折扣，1.000 表示不打折', max_digits=5, verbose_name='等级折扣')),
                ('contact', models.CharField(blank=True, max_length=50, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='电话')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='材料代码')),
                ('name', models.CharField(max_length=50, verbose_name='材料名称')),
                ('unit', models.CharField(choices=[('元/kg', '元/kg'), ('元/t', '元/t')], default='元/kg', max_length=10, verbose_name='计价单位')),
                ('density', models.DecimalField(decimal_places=3, default=0, help_text='用于理论重量计算，如铜 8.89、铝 2.703、XLPE 0.92、PVC 1.40', max_digits=6, verbose_name='密度 g/cm³')),
                ('loss_rate', models.DecimalField(decimal_places=2, default=2, help_text='投料损耗，成本按 (1+损耗率) 放大', max_digits=5, verbose_name='损耗率 %')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='备注')),
            ],
            options={
                'verbose_name': '材料',
                'verbose_name_plural': '材料',
            },
        ),
        migrations.CreateModel(
            name='PricingParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='某某电缆有限公司', max_length=100, verbose_name='公司名称')),
                ('company_phone', models.CharField(blank=True, max_length=50, verbose_name='联系电话')),
                ('company_address', models.CharField(blank=True, max_length=200, verbose_name='地址')),
                ('quote_note', models.CharField(blank=True, default='以上报价基于当日铜价，有效期后请重新询价；数量与交期以合同为准。', max_length=300, verbose_name='报价单脚注')),
                ('target_margin_pct', models.DecimalField(decimal_places=2, default=Decimal('20'), max_digits=5, verbose_name='目标毛利率 %')),
                ('min_margin_pct', models.DecimalField(decimal_places=2, default=Decimal('8'), help_text='低于该毛利的折扣需要经理审批', max_digits=5, verbose_name='最低毛利率 %')),
                ('tax_rate_pct', models.DecimalField(decimal_places=2, default=Decimal('13'), max_digits=5, verbose_name='增值税率 %')),
                ('price_with_tax', models.BooleanField(default=True, verbose_name='报价含税')),
                ('process_fee_base', models.DecimalField(decimal_places=2, default=Decimal('150'), max_digits=10, verbose_name='加工费基础 元/km')),
                ('process_fee_per_section', models.DecimalField(decimal_places=3, default=Decimal('1.200'), help_text='加工费 = 基础 + 系数×截面合计 + 材料成本×百分比', max_digits=8, verbose_name='加工费/截面系数 元/(km·mm²)')),
                ('process_fee_pct_material', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=5, verbose_name='加工费材料加成 %')),
                ('quote_valid_days', models.IntegerField(default=3, verbose_name='报价有效期（天）')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '计价参数',
                'verbose_name_plural': '计价参数',
            },
        ),
        migrations.CreateModel(
            name='CableSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout', models.CharField(help_text='规范写法，如 3x120+1x70（x 为半角，多芯等截面如 4x16）', max_length=50, verbose_name='规格代码')),
                ('voltage', models.CharField(blank=True, max_length=20, verbose_name='电压等级')),
                ('cores_total', models.IntegerField(default=1, verbose_name='总芯数')),
                ('section_total', models.DecimalField(decimal_places=1, default=0, help_text='Σ(芯数×截面)，用于加工费分档', max_digits=8, verbose_name='截面合计 mm²')),
                ('conductor_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='导体重量 kg/km')),
                ('insulation_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='绝缘重量 kg/km')),
                ('sheath_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='护套重量 kg/km')),
                ('filler_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='填充绕包重量 kg/km')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='quoter.cableseries', verbose_name='系列')),
                ('conductor_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specs_conductor', to='quoter.material', verbose_name='导体材料')),
            ],
            options={
                'verbose_name': '规格',
                'verbose_name_plural': '规格库',
                'ordering': ['series__code', 'layout'],
            },
        ),
        migrations.AddField(
            model_name='cableseries',
            name='insulation',
            field=models.ForeignKey(limit_choices_to={'code__in': ['XLPE', 'PVC']}, on_delete=django.db.models.deletion.PROTECT, related_name='series_insulation', to='quoter.material', verbose_name='绝缘材料'),
        ),
        migrations.AddField(
            model_name='cableseries',
            name='sheath_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='series_sheath', to='quoter.material', verbose_name='护套材料'),
        ),
        migrations.CreateModel(
            name='MaterialPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='生效日期')),
                ('price', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='单价')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='quoter.material', verbose_name='材料')),
            ],
            options={
                'verbose_name': '材料价格',
                'verbose_name_plural': '材料价格',
                'ordering': ['-date', 'material__code'],
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, unique=True, verbose_name='报价单号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('valid_until', models.DateField(verbose_name='有效期至')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待审批'), ('approved', '已审批'), ('rejected', '已驳回')], default='draft', max_length=10, verbose_name='状态')),
                ('discount', models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text='在目录价基础上的折扣，0.95 即 95 折', max_digits=5, verbose_name='整单折扣')),
                ('base_cu_price', models.DecimalField(decimal_places=4, default=0, help_text='报价时铜价快照，打印在报价单上', max_digits=10, verbose_name='基准铜价 元/kg')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations_created', to=settings.AUTH_USER_MODEL, verbose_name='业务员')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='quoter.customer', verbose_name='客户')),
            ],
            options={
                'verbose_name': '报价单',
                'verbose_name_plural': '报价单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_text', models.CharField(blank=True, max_length=100, verbose_name='规格快照')),
                ('length_m', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='长度 m')),
                ('list_price_per_m', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='目录单价 元/m')),
                ('final_price_per_m', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='成交单价 元/m')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='金额 元')),
                ('cost_detail', models.JSONField(blank=True, default=dict, verbose_name='计价明细快照')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quoter.quotation', verbose_name='报价单')),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quote_items', to='quoter.cablespec', verbose_name='规格')),
            ],
            options={
                'verbose_name': '报价明细',
                'verbose_name_plural': '报价明细',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='cablespec',
            constraint=models.UniqueConstraint(fields=('series', 'layout'), name='uniq_series_layout'),
        ),
        migrations.AddConstraint(
            model_name='materialprice',
            constraint=models.UniqueConstraint(fields=('material', 'date'), name='uniq_material_date'),
        ),
    ]
