# Generated by Django 6.1 on 2026-08-31 07:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cableseries',
            name='lay_factor',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.02'), max_digits=5, verbose_name='绞合系数'),
        ),
    ]
