# Generated by Django 6.1 on 2026-08-31 07:40

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoter', '0002_alter_cableseries_lay_factor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialprice',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': '材料价格', 'verbose_name_plural': '材料价格'},
        ),
        migrations.AddField(
            model_name='cableseries',
            name='armor_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='series_armor', to='quoter.material', verbose_name='铠装/屏蔽材料'),
        ),
        migrations.AddField(
            model_name='cableseries',
            name='has_armor',
            field=models.BooleanField(default=False, help_text='如 YJV22 钢带铠装、屏蔽型电缆', verbose_name='有铠装/屏蔽'),
        ),
        migrations.AddField(
            model_name='cablespec',
            name='armor_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='屏蔽/铠装重量 kg/km'),
        ),
        migrations.AddField(
            model_name='materialprice',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='录入时间'),
        ),
        migrations.AddField(
            model_name='materialprice',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='LME 等外币来源抓取时的换算汇率（留痕）', max_digits=10, null=True, verbose_name='汇率 USD/CNY'),
        ),
        migrations.AddField(
            model_name='materialprice',
            name='is_auto',
            field=models.BooleanField(default=False, verbose_name='自动获取'),
        ),
        migrations.AddField(
            model_name='materialprice',
            name='premium',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='计价时叠加在基准价上，可为负', max_digits=10, verbose_name='升贴水 元/kg'),
        ),
        migrations.AddField(
            model_name='materialprice',
            name='source',
            field=models.CharField(choices=[('manual', '手工录入/修正'), ('changjiang', '长江现货'), ('shfe', '上海期货'), ('lme', 'LME')], default='manual', max_length=20, verbose_name='价格来源'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='cu_price_source',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='铜价来源'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='cu_price_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='铜价生效时间'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='freight',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='整单运费，计入报价合计（销售报价 = 货款 + 运费）', max_digits=12, verbose_name='运费 元'),
        ),
        migrations.AlterField(
            model_name='materialprice',
            name='price',
            field=models.DecimalField(decimal_places=4, help_text='统一换算为 元/kg 后存储', max_digits=12, verbose_name='单价'),
        ),
        migrations.AlterField(
            model_name='pricingparams',
            name='process_fee_pct_material',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='制造费用分摊：按材料成本的百分比计入', max_digits=5, verbose_name='人工及制造费用(材料成本%)'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='base_cu_price',
            field=models.DecimalField(decimal_places=4, default=0, help_text='报价时铜价快照（含升贴水），打印在报价单上', max_digits=10, verbose_name='基准铜价 元/kg'),
        ),
    ]
