# Generated by Django 6.1 on 2026-08-31 08:00

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoter', '0003_alter_materialprice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingparams',
            name='boss_threshold_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('500000'), help_text='整单金额达到该值时，经理审批后还需老板终审', max_digits=14, verbose_name='大单审批阈值 元'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('pending', '待审批'), ('boss_pending', '待老板终审'), ('approved', '已审批'), ('rejected', '已驳回')], default='draft', max_length=20, verbose_name='状态'),
        ),
        migrations.CreateModel(
            name='CustomerTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_length_m', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='起订总长度 m')),
                ('discount', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='折扣')),
                ('note', models.CharField(blank=True, max_length=100, verbose_name='备注')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='quoter.customer', verbose_name='客户')),
            ],
            options={
                'verbose_name': '客户阶梯价',
                'verbose_name_plural': '客户阶梯价',
                'ordering': ['customer', 'min_length_m'],
                'constraints': [models.UniqueConstraint(fields=('customer', 'min_length_m'), name='uniq_tier_customer_length')],
            },
        ),
    ]
