# Generated by Django 6.1 on 2026-08-31 08:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoter', '0004_pricingparams_boss_threshold_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, unique=True, verbose_name='订单号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='订单金额 元')),
                ('status', models.CharField(choices=[('production', '生产中'), ('shipped', '已发货'), ('done', '已完成'), ('cancelled', '已取消')], default='production', max_length=20, verbose_name='状态')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='quoter.customer', verbose_name='客户')),
                ('quotation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='quoter.quotation', verbose_name='来源报价单')),
            ],
            options={
                'verbose_name': '销售订单',
                'verbose_name_plural': '销售订单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='回款日期')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='回款金额 元')),
                ('method', models.CharField(blank=True, help_text='电汇/承兑/现金等', max_length=20, verbose_name='方式')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='quoter.salesorder', verbose_name='订单')),
            ],
            options={
                'verbose_name': '回款记录',
                'verbose_name_plural': '回款记录',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
