# Generated by Django 6.1 on 2026-08-31 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoter', '0005_salesorder_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteSendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_to', models.CharField(help_text='多个邮箱用逗号分隔', max_length=200, verbose_name='收件人')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_logs', to='quoter.quotation', verbose_name='报价单')),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes_sent', to=settings.AUTH_USER_MODEL, verbose_name='发送人')),
            ],
            options={
                'verbose_name': '报价发送记录',
                'verbose_name_plural': '报价发送记录',
                'ordering': ['-sent_at'],
            },
        ),
    ]
