# Generated by Django 6.1 on 2026-08-31 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoter', '0006_quotesendlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingparams',
            name='portal_code',
            field=models.CharField(blank=True, default='', help_text='留空则无需访问码；设置后客户需输入访问码进入', max_length=30, verbose_name='门户访问码'),
        ),
        migrations.AddField(
            model_name='pricingparams',
            name='portal_enabled',
            field=models.BooleanField(default=True, verbose_name='启用客户自助询价门户'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='share_token',
            field=models.CharField(blank=True, db_index=True, default='', help_text='生成后客户可通过 /q/<token>/ 免登录查看并签收报价单', max_length=40, verbose_name='客户链接令牌'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='客户签收时间'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='signed_by',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='签收人'),
        ),
        migrations.CreateModel(
            name='InquiryLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100, verbose_name='公司名称')),
                ('contact_name', models.CharField(max_length=50, verbose_name='联系人')),
                ('phone', models.CharField(max_length=30, verbose_name='联系电话')),
                ('note', models.TextField(blank=True, verbose_name='留言')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('status', models.CharField(choices=[('new', '新线索'), ('handled', '已处理')], default='new', max_length=10, verbose_name='状态')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_handled', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_leads', to='quoter.quotation', verbose_name='转出的报价单')),
            ],
            options={
                'verbose_name': '询价线索',
                'verbose_name_plural': '询价线索',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InquiryLeadItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_text', models.CharField(blank=True, max_length=100, verbose_name='规格快照')),
                ('length_m', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='长度 m')),
                ('quoted_price_per_m', models.DecimalField(decimal_places=4, default=0, help_text='客户在门户看到的价格（目录价，不含成本信息）', max_digits=10, verbose_name='门户目录价快照 元/m')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quoter.inquirylead', verbose_name='线索')),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lead_items', to='quoter.cablespec', verbose_name='规格')),
            ],
            options={
                'verbose_name': '询价明细',
                'verbose_name_plural': '询价明细',
            },
        ),
    ]
