# Generated by Django 6.1 on 2026-08-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoter', '0007_pricingparams_portal_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cableseries',
            name='armor_steel_table',
            field=models.JSONField(blank=True, default=dict, help_text='按成缆外径段配单层钢带厚度(mm)，如 {"15": 0.2, "25": 0.3, "40": 0.5}；留空用内置四档', verbose_name='铠装钢带厚度表'),
        ),
    ]
