# Generated by Django 6.1 on 2026-09-01 02:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoter', '0008_cableseries_armor_steel_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='currency',
            field=models.CharField(choices=[('CNY', '人民币'), ('USD', '美元'), ('EUR', '欧元')], default='CNY', max_length=3, verbose_name='币种'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.0000'), help_text='报价币种对人民币汇率（1 外币 = N 人民币），人民币报价填 1', max_digits=10, verbose_name='汇率'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='currency',
            field=models.CharField(choices=[('CNY', '人民币'), ('USD', '美元'), ('EUR', '欧元')], default='CNY', max_length=3, verbose_name='币种'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=10, verbose_name='汇率'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='订单金额'),
        ),
    ]
